services:
  astro-build:
    build: .
    container_name: astro-build
    volumes:
      - ./dist:/app/dist
    command: ["pnpm", "run", "build"]
    networks:
      - redream_net
      - caddy_net

networks:
  redream_net:
    name: redream_net
  caddy_net:
    external: true
    name: caddy_net